#!/bin/bash
mkdir "C:/Users/andre/personal-knowledge/Attachments/Git and GitHub - How to Revert a Single File"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Git and GitHub - How to Revert a Single File"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Git and GitHub - How to Revert a Single File"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Git and GitHub - How to Revert a Single File"
mkdir "C:/Users/andre/personal-knowledge/Attachments/The evolution of virtual fences - A review"
mkdir "C:/Users/andre/personal-knowledge/Attachments/The FAIR Guiding Principles for scientific data management and stewardship"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Daubenmire Versus Line-Point Intercept - A Response to Thacker et al. (2015)"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Determining learning and behavioural response to a virtual fence for dairy cows"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Virtual Fences Successfully Contain Cattle Over a Wide Range of Stocking Densities and at Stubble Heights Below Common Riparian Management Targets"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Ten Simple Rules for Digital Data Storage"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Tech-Savvy Beef Cattle How Heifers Respond to Moving Virtual Fence Lines"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Confusion among three common plant cover definitions may result in data unsuited for comparison"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Get More Out of Obsidian - The 6 Note Types to Elevate Your PKM"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Dataview sorting by creation date - Help"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Convert a scanned pdf to text with Linux command line using OCRmyPDF"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Convert a scanned pdf to text with Linux command line using OCRmyPDF"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Convert a scanned pdf to text with Linux command line using OCRmyPDF"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Balancing horizontal accuracy and data collection efficiency with mapping-grade GPS receivers"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Assessing herbivore foraging behavior with GPS collars in a semiarid grassland"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Opportunities to Apply Precision Livestock Management on Rangelands"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Effects of Moose Movement and Habitat Use on GPS Collar Performance"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Accuracy and performance of low-feature GPS collars deployed on bison Bison bison and caribou Rangifer tarandus"
mkdir "C:/Users/andre/personal-knowledge/Attachments/GPS Error in Studies Addressing Animal Movements and Activities"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Plant Cover Estimation - A Contiguous Daubenmire Frame"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Plant Cover Estimation - A Contiguous Daubenmire Frame"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - DataView - Find duplicate values - Help"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - Get More Out of Obsidian - The 6 Note Types to Elevate Your PKM"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - Understanding Landscape Use Patterns of Livestock as a Consequence of Foraging Behavior"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - Ten practical questions to improve data quality"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - A fence runs through it - A call for greater attention to the influence of fences on wildlife and ecosystems"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - searching [Zotero Documentation]"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - Do Young Calves Influence Movement Patterns of Nursing Raramuri Criollo Cows on Rangeland"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - Classifying season long livestock grazing behavior with the use of a low-cost GPS and accelerometer"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - Classifying season long livestock grazing behavior with the use of a low-cost GPS and accelerometer"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - Virtual Fencing Effectively Excludes Cattle from Burned Sagebrush Steppe"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - A GPS-based Evaluation of Factors Commonly Used to Adjust Cattle Stocking Rates on Both Extensive and Mountainous Rangelands"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - A GPS-based Evaluation of Factors Commonly Used to Adjust Cattle Stocking Rates on Both Extensive and Mountainous Rangelands"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - Using Virtual Fencing to Create Fuel Breaks in the Sagebrush Steppe"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Book - Version Control.md"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Book - General Workflow.md"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Book - Non-Linear Development of Your Project with “Branches”.md"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Book - The Turing Way - Git for research projects.md"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Book - The Turing Way - Version Control for Data.md"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Book - The Turing Way - Code Testing - Code Testing.md"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Book - The Turing Way - Code Testing - General guidance and good practice for testing.md"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - Spatiotemporal cattle data—a plea for protocol standardization"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - Spatiotemporal cattle data—a plea for protocol standardization"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - The FAIR Guiding Principles for scientific data management and stewardship"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - The FAIR Guiding Principles for scientific data management and stewardship"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - Challenges and Opportunities of Open Data in Ecology"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - Individual Animal Selection Has the Potential to Improve Uniformity of Grazing on Foothill Rangeland"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - Monitoring grazing use - Strategies for leveraging technology and adapting to variability"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Book -  - DuckDB - an Embeddable Analytical Database.md"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - Cross-Fencing on Private US Rangelands - Financial Costs and Producer Risks"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - Comparative costs for fence construction"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Document - Paddock Design, Fencing and Water Systems for Controlled Grazing.md"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Document - Electric Fencing for Serious Graziers.md"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Accuracy and performance of low-feature GPS collars deployed on bison Bison bison and caribou Rangifer tarandus"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Assessing herbivore foraging behavior with GPS collars in a semiarid grassland"
mkdir C:/Users/andre/personal-knowledge/Attachments/augustineAssessingHerbivoreForaging2013
mkdir C:/Users/andre/personal-knowledge/Attachments/baileyOpportunitiesApplyPrecision2021a
mkdir "C:/Users/andre/personal-knowledge/Attachments/Balancing horizontal accuracy and data collection efficiency with mapping-grade GPS receivers"
mkdir C:/Users/andre/personal-knowledge/Attachments/bonhamPlantCoverEstimation2004
mkdir C:/Users/andre/personal-knowledge/Attachments/bonhamPlantCoverEstimation2004a
mkdir C:/Users/andre/personal-knowledge/Attachments/campbellTechSavvyBeefCattle2017
mkdir "C:/Users/andre/personal-knowledge/Attachments/Confusion among three common plant cover definitions may result in data unsuited for comparison"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Convert a scanned pdf to text with Linux command line using OCRmyPDF"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Dataview sorting by creation date - Help"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Daubenmire Versus Line-Point Intercept - A Response to Thacker et al. (2015)"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Determining learning and behavioural response to a virtual fence for dairy cows"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Effects of Moose Movement and Habitat Use on GPS Collar Performance"
mkdir C:/Users/andre/personal-knowledge/Attachments/frankBalancingHorizontalAccuracy2014
mkdir C:/Users/andre/personal-knowledge/Attachments/ganskoppGPSErrorStudies2007
mkdir "C:/Users/andre/personal-knowledge/Attachments/Get More Out of Obsidian - The 6 Note Types to Elevate Your PKM"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Git and GitHub - How to Revert a Single File"
mkdir "C:/Users/andre/personal-knowledge/Attachments/GPS Error in Studies Addressing Animal Movements and Activities"
mkdir C:/Users/andre/personal-knowledge/Attachments/hartTenSimpleRules2016
mkdir C:/Users/andre/personal-knowledge/Attachments/jefferyfehmiConfusionThreeCommon2010
mkdir C:/Users/andre/personal-knowledge/Attachments/jeroSimulatedRuminantDigestion2022
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - A fence runs through it - A call for greater attention to the influence of fences on wildlife and ecosystems"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - A GPS-based Evaluation of Factors Commonly Used to Adjust Cattle Stocking Rates on Both Extensive and Mountainous Rangelands"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - Classifying season long livestock grazing behavior with the use of a low-cost GPS and accelerometer"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - DataView - Find duplicate values - Help"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - Do Young Calves Influence Movement Patterns of Nursing Raramuri Criollo Cows on Rangeland"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - Get More Out of Obsidian - The 6 Note Types to Elevate Your PKM"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - Publishing Ecological Data in a Repository - An Easy Workflow for Everyone"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - searching [Zotero Documentation]"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - Ten practical questions to improve data quality"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - The Grass is Greener on the Other Side - Developing Climate-Smart Beef and Bison Commodities"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - Understanding Landscape Use Patterns of Livestock as a Consequence of Foraging Behavior"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - Virtual Fencing Effectively Excludes Cattle from Burned Sagebrush Steppe"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Journal Article - What's in a name Standardizing terminology for the enhancement of research, extension, and industry applications of virtual fence us"
mkdir C:/Users/andre/personal-knowledge/Attachments/jungAccuracyPerformanceLowfeature2018
mkdir C:/Users/andre/personal-knowledge/Attachments/lomaxDeterminingLearningBehavioural2017
mkdir C:/Users/andre/personal-knowledge/Attachments/martynDaubenmireLinePointIntercept2015
mkdir C:/Users/andre/personal-knowledge/Attachments/moenEffectsMooseMovement1996
mkdir "C:/Users/andre/personal-knowledge/Attachments/Opportunities to Apply Precision Livestock Management on Rangelands"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Plant Cover Estimation - A Contiguous Daubenmire Frame"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Tech-Savvy Beef Cattle How Heifers Respond to Moving Virtual Fence Lines"
mkdir "C:/Users/andre/personal-knowledge/Attachments/Ten Simple Rules for Digital Data Storage"
mkdir "C:/Users/andre/personal-knowledge/Attachments/The evolution of virtual fences - A review"
mkdir "C:/Users/andre/personal-knowledge/Attachments/The FAIR Guiding Principles for scientific data management and stewardship"
mkdir C:/Users/andre/personal-knowledge/Attachments/umstatterEvolutionVirtualFences2011
mkdir "C:/Users/andre/personal-knowledge/Attachments/Virtual Fences Successfully Contain Cattle Over a Wide Range of Stocking Densities and at Stubble Heights Below Common Riparian Management Targets"
mkdir C:/Users/andre/personal-knowledge/Attachments/wilkinsonFAIRGuidingPrinciples2016
